### ISSUE TITLE
Is PlumX compatible with OJS 2.4.8.5 ?

### ISSUE THREAD

**Issue by sergiobmartins** [ulsdevteam/ojs-plum-plugin#1]

**Comment by sergiobmartins** [comment]
Hi, I just uploaded the file into /plugins/generic/plumAnalytics.
When I logged as Journal Manager and will go to enable the PlumX plugin, it looks the names, fields are not being recognized:

##plugins.generic.plumAnalytics.manager.plumAnalyticsSettings##

But I guess I found the issue. In the Locate there is no translation to Portuguese/BR.
So, If I just duplicate the one in the folder en_US and create a new one as pt_BR (for Portuguese Brazil) and another one as es_ES (for Spanish) this will work, right?

**Comment by ctgraham** [comment]
Yes, you will need to add new translations for non English locales.  If you do perform any translation work, please feel free to contribute that back, either as a pull request, or just by sending me the files.  Thanks!
