### ISSUE TITLE
OJS3.3 compatibility

### ISSUE THREAD

**Issue by TobiasWantzen** [ulsdevteam/ojs-plum-plugin#11]
So far the plum plugin is not compatible with OJS3.3. Please adjust the plugin to the latest version of OJS.

Thanks,
Tobias

**Comment by ctgraham** [comment]
Hi, @TobiasWantzen .  Are you seeing a specific error message or failure?  We are running the plugin in OJS 3.3.0-11 and about to update our journals to 3.3.0-13, with this plugin.

**Comment by TobiasWantzen** [comment]
@ctgraham Thank you for pointing this out! We upgraded from 3.2.1.1 to 3.3.0-13. The person who upgraded told me that he had to delete the plugin, "in order to prevent crash".
Thanks to your post I reinstalled the plugin and, as far as I can see, it runs without problems.

So please close this issue – there seems to be no issue.
Tobias
