### ISSUE TITLE
Error when using 1.4.0.0 with OJS 3.3.0.8 and PHP 8.1.14

### ISSUE THREAD

**Issue by felixhelix** [ulsdevteam/ojs-plum-plugin#12]
Hi, we just updated our Server to PHP 8.1.14.

When trying to assess the settings page of the plugin, the following error occurs:

PHP Fatal error:  Declaration of PlumAnalyticsSettingsForm::fetch($request) must be compatible with Form::fetch($request, $template = null, $display = false) in /var/www/html/plugins/generic/plumAnalytics/PlumAnalyticsSettingsForm.inc.php on line 92

Plugin Version 1.4.0.0
OJS 3.3.0.8
PHP 8.1.14

Yours

Stephan Henn

**Comment by wopsononock** [comment]
Addressed in https://github.com/ulsdevteam/ojs-plum-plugin/releases/tag/v1.4.0-1
