### ISSUE TITLE
Upstream URL change

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ojs-plum-plugin#5]
https://forum.pkp.sfu.ca/t/plumx-metrics-widget-code-change-announcement

>We are making some changes to our widget code, specifically related to the widget CDN URL, which we are replacing with a logical URL due to AWS account migration. Anyone using the artifact widget will need to make a slight change the widget javascript to reflect the new server location.

> In the current script you will need to remove “d39af2mgp1pqhg.cloudfront.net” and replace it with “cdn.plu.mx”. The current widget server will re-direct for the next few months, but please make sure you have this change completed by the end of February 2019 if possible to avoid disruption.

**Comment by sergiobmartins** [comment]
Hi @ctgraham, by talking with Stephanie from PlumX, we found an issue in your plugin. In the file:
plugins/generic/plumAnalytics/pageTagPlumWidget.tpl

there is an extra slash in the link:
a href="https://plu.mx/a**/**?doi=

today it's this way:

{if $htmlPrefix}{$htmlPrefix}{/if}
 
<a href="https://plu.mx/a**/**?doi={$articleDOI|escape}" class="{$widgetType|escape}" {if $hideWhenEmpty}data-hide-when-empty="{$hideWhenEmpty|escape}" {/if}{if $hidePrint}data-hide-print="{$hidePrint|escape}" {/if}{if $orientation}data-orientation="{$orientation|escape}" {/if}{if $popup}data-popup="{$popup|escape}" {/if}{if $border}data-border="{$border|escape}"{/if}{if $width}data-width="{$width|escape}"{/if}></a>

{if $htmlSuffix}{$htmlSuffix}{/if}

but the correct should be this way:

today it's this way:

{if $htmlPrefix}{$htmlPrefix}{/if}
 
<a href="https://plu.mx/a?doi={$articleDOI|escape}" class="{$widgetType|escape}" {if $hideWhenEmpty}data-hide-when-empty="{$hideWhenEmpty|escape}" {/if}{if $hidePrint}data-hide-print="{$hidePrint|escape}" {/if}{if $orientation}data-orientation="{$orientation|escape}" {/if}{if $popup}data-popup="{$popup|escape}" {/if}{if $border}data-border="{$border|escape}"{/if}{if $width}data-width="{$width|escape}"{/if}></a>

{if $htmlSuffix}{$htmlSuffix}{/if}

if you go to PlumX website with the link using an extra slash, it will show "Page not Found". Without the extra slash, if will show the article correctly.

**Comment by ctgraham** [comment]
Thanks, @sergiobmartins.  A new release has been packaged for OJS 2.x, and a commit has been made to the master branch for OJS 3.x, pending an upcoming release.

**Comment by ctgraham** [comment]
I've updated the endpoint in 2.x to be `https://plu.mx/plum/a/?` per https://plu.mx/plum/developers/widgets.

Requested confirmation from Stephanie Faulkner in https://forum.pkp.sfu.ca/t/solucion-error-en-plugin-plumanalityc/50526 .

**Comment by ctgraham** [comment]
Issue still exists in 3.x releases.

**Comment by ctgraham** [comment]
Resolved.
