### ISSUE TITLE
Installed on 3.1.2-1 and not working

### ISSUE THREAD

**Issue by marcbria** [ulsdevteam/ojs-plum-plugin#7]
Hi @ctgraham 

I installed manually and I can't make it work.
No log info and plugin is not shown under the article.
Any clue about how to debug or what could be failing?

Thanks for your time,
m.

**Comment by marcbria** [comment]
Shit... missed to clear server cache. :-)
Forget this.

Thanks,
m.

**Comment by ctgraham** [comment]
Was the old article page cached in OJS's Template Cache, or was it something different?

**Comment by marcbria** [comment]
I think was OJS old article page cache, but you know... when something fails and you are in a hurry, you touch 3-4 things at the same time and then you can never say. :-(

I will be more methodic if it happens to me in a new journal.
