### ISSUE TITLE
Metrics Detail

### ISSUE THREAD

**Issue by ainulrafiq** [ulsdevteam/ojs-plum-plugin#9]
Dear all,

does the plugin will function fully as from the other system? Ex: the metrics by here https://plu.mx/plum/a/0w38NKxZXRkMtF9Apdr9EH1PfKQ1-V2pVED3LgDYU0I/ , it visualizing many matrics: Citation, Usage, Caption, Social Media, and comparing it with this https://myjurnal.poltekkes-kdi.ac.id/index.php/HIJP/article/view/193 that just visualizing Caption and Social Media.

Thank you!

**Comment by ctgraham** [comment]
Yes, this plugin is an implementation of the standard [Artifact Widget](https://plu.mx/developers/widgets), supporting all categories of metrics.  If you click through to PlumX's metrics for [your specific DOI](https://plu.mx/plum/a/?doi=10.36990/hijp.vi.193), you will see the data PlumX has collected for this article.

Usage metrics may only be captured by PlumX if you are a subscriber, and and if you are providing those metrics to PlumX.

**Comment by ainulrafiq** [comment]
According to FAQ here https://plumanalytics.com/learn/about-metrics/usage-metrics/ , usage metrics collected from OJS, but if we see the DOI here https://plu.mx/plum/a/?doi=10.36990/hijp.v11i2.133 , the metrics only from Mendeley..Thanks!

**Comment by ctgraham** [comment]
The transfer of usage metrics is facilitated by the [SUSHI-Lite plugin](https://github.com/ulsdevteam/ojs-sushiLite-plugin/).  Note that [the details here](https://plumanalytics.com/integrate/load-your-data/ojs_integration/) specify that this is for "Plum Customers".  If you are a Plum customer, they should be able to assist you with confirming the setup.  If you are not a Plum customer, you can inquire as to whether this is now available without a subscription.

**Comment by ainulrafiq** [comment]
Ah I see.. Thank you so much for the details..
